import test from 'node:test';
import assert from 'node:assert/strict';
import { runDeploymentSmoke } from '../scripts/post-deploy-smoke.js';

const json = (body, status = 200) => new Response(JSON.stringify(body), {
  status,
  headers: { 'content-type': 'application/json' },
});

function healthyFetch({ staleOnce = false, devMode = false, monetization = 'paused', database = 'supabase', serviceOverrides = {} } = {}) {
  let healthCalls = 0;
  return async input => {
    const url = new URL(input);
    if (url.pathname === '/health/ready') {
      healthCalls += 1;
      const version=staleOnce && healthCalls===1 ? '6.12.0-rc20' : '6.27.0-rc35';
      return json({
        ok:true,status:'ready',version,releaseCandidate:'RC35',checks:{
          supabase:{ok:true,status:'ok',attempts:1},
          schema:{ok:true,status:'ok',fingerprint:'abc',expectedFingerprint:'abc'},
          backendSecurity:{ok:true,status:'ok'},
          telegramConfigured:true,
          recentSupabaseAuthFailures:0,
        },
      });
    }
    if (url.pathname === '/health') {
      healthCalls += 1;
      return json({
        ok: true,
        readiness:{ok:true,status:'ready'},
        version: staleOnce && healthCalls === 1 ? '6.12.0-rc20' : '6.27.0-rc35',
        releaseCandidate: 'RC35',
        devMode,
        database,
        monetization,
        adminSecurity: 'enabled',
        adminDevModeIsolation: 'enabled',
        backendSecurityContract: 'enabled',
        supabaseSchemaDriftGuard: 'enabled',
        supabaseSchemaDriftSelfTest: 'enabled',
        productionMonitor: 'enabled',
        productionMonitorSelfTest: 'enabled',
        rollbackVerification: 'enabled',
        providerDataReliability: 'enabled',
        providerDataReliabilitySelfTest: 'enabled',
        providerSloObservability: 'enabled',
        providerSloSelfTest: 'enabled',
        multiProviderDataService: 'enabled',
        openLigaDbStandingsFallback: 'enabled',
        openLigaDbEventFallback: 'enabled',
        teamPlayerSeasonStats: 'enabled',
        structuredAvailability: 'enabled',
        playerRoleAvailability: 'enabled',
        playerRoleHydration: 'enabled',
        lineupQualityGuard: 'enabled',
        lineupSemanticReliability: 'enabled',
        freshnessAwareDataTrust: 'enabled',
        xgSemanticQualityGuard: 'enabled',
        eventSemanticQualityGuard: 'enabled',
        statisticsSemanticQualityGuard: 'enabled',
        oddsSemanticQualityGuard: 'enabled',
        availabilitySemanticQualityGuard: 'enabled',
        sourceProvenance: 'enabled',
        aiAnalysisQualityGate: 'enabled',
        aiAnalysisQualityGateSelfTest: 'enabled',
        telegramMiniAppE2E: 'enabled',
        telegramMiniAppE2ESelfTest: 'enabled',
        telegramWebhookPersistentDedupe: 'enabled',
        telegramWebhookPersistentDedupeSelfTest: 'enabled',
        telegramWebhookDedupeObservability: 'enabled',
        telegramWebhookDedupeObservabilitySelfTest: 'enabled',
        supabaseProbeConfirmation: 'enabled',
        supabaseProbeConfirmationSelfTest: 'enabled',
        supabaseSchemaProbeConfirmation: 'enabled',
        supabaseSchemaProbeConfirmationSelfTest: 'enabled',
        cloudflareDeploymentGate: 'enabled',
        browserSecurityPolicy: 'enabled',
        failClosedDeployment: 'enabled',
        interactionSafety: 'enabled',
        actionDeduplication: 'enabled',
        staleResponseGuard: 'enabled',
        profileFailSoft: 'enabled',
        entityNavigationSafety: 'enabled',
        personalDataStateSafety: 'enabled',
        asyncEntityGuard: 'enabled',
        personalDataWriteConsistency: 'enabled',
        reminderWriteConfirmation: 'enabled',
        readWriteRaceGuard: 'enabled',
        analysisHistoryTransition: 'enabled',
        historyStaleGuard: 'enabled',
        immediateAnalysisHandoff: 'enabled',
        russianUiLocalization: 'enabled',
        adminRussianLocalization: 'enabled',
        prematchRussianLocalization: 'enabled',
        dynamicRussianLocalization: 'enabled',
        adminTextHumanization: 'enabled',
        matchCenterRussianLocalization: 'enabled',
        mediaLaunchHardening: 'enabled',
        telegramWebhookDedupe: 'enabled',
        telegramWebhookBurstGuard: 'enabled',
        newsSourceTrustGate: 'enabled',
        publicLegalPages: 'enabled',
        publicStatusPage: 'enabled',
        mediaLaunchPackage: 'enabled',
        mediaDeepLinkAttribution: 'enabled',
        firstPartyGrowthAnalytics: 'enabled',
        launchFunnelAnalytics: 'enabled',
        launchPrivacyGuard: 'enabled',
        launchSimulation: 'enabled',
        conversionUx: 'enabled',
        highIntentSearchFallback: 'enabled',
        newsReturnLoop: 'enabled',
        realLaunchDrill: 'enabled',
        searchNormalization: 'enabled',
        searchOutcomeAnalytics: 'enabled',
        searchRetryUx: 'enabled',
        searchQualitySelfTest: 'enabled',
        zeroResultRecovery: 'enabled',
        teamFixtureDiscovery: 'enabled',
        sharedFixtureDiscoveryCache: 'enabled',
        extendedTeamCalendar: 'enabled',
        recentMatchFallback: 'enabled',
        matchSelectionIntelligence: 'enabled',
        primaryMatchRecommendation: 'enabled',
        officialMatchPriority: 'enabled',
        selectionReasonUx: 'enabled',
        matchSelectionSelfTest: 'enabled',
        oneTapAiHandoff: 'enabled',
        telegramAutoQuickBrief: 'enabled',
        cachedFullAnalysisHandoff: 'enabled',
        directFixtureDeepLink: 'enabled',
        handoffFunnelTracking: 'enabled',
        oneTapHandoffSelfTest: 'enabled',
        aiFreshnessGuard: 'enabled',
        preKickoffRecheck: 'enabled',
        userScopedFreeRecheck: 'enabled',
        lineupFreshnessWindow: 'enabled',
        adaptiveAnalysisTtl: 'enabled',
        analysisFreshnessSelfTest: 'enabled',
        preKickoffChangeDetection: 'enabled',
        analysisDeltaSummary: 'enabled',
        recheckMateriality: 'enabled',
        telegramRecheckDelta: 'enabled',
        analysisDeltaSelfTest: 'enabled',
        kickoffHandoffGuard: 'enabled',
        prematchAdviceFreeze: 'enabled',
        liveContextHandoff: 'enabled',
        finishedAnalysisArchive: 'enabled',
        kickoffHandoffSelfTest: 'enabled',
        postMatchAiReview: 'enabled',
        immutablePrematchComparison: 'enabled',
        calibrationFeedbackReview: 'enabled',
        telegramPostMatchReview: 'enabled',
        postMatchReviewSelfTest: 'enabled',
        postMatchReturnLoop: 'enabled',
        analyzedMatchReturn: 'enabled',
        postMatchReturnDedupe: 'enabled',
        postMatchReturnOptOut: 'enabled',
        postMatchReturnQuotaGuard: 'enabled',
        postMatchReturnSelfTest: 'enabled',
        publicAiTrackRecord: 'enabled',
        verifiedTrackRecordOnly: 'enabled',
        smallSampleTrustGuard: 'enabled',
        noWinRateTrustUx: 'enabled',
        telegramAiTrackRecord: 'enabled',
        aiTrackRecordSelfTest: 'enabled',
        mediaFixtureDeepLinks: 'enabled',
        shareableMatchCards: 'enabled',
        shareAttribution: 'enabled',
        deepLinkAutoAnalysis: 'enabled',
        telegramNativeShare: 'enabled',
        fixtureDeepLinkSelfTest: 'enabled',
        distributedAnalysisLock: 'enabled',
        viralFixtureCollapse: 'enabled',
        crossInstanceAnalysisDedupe: 'enabled',
        analysisLockFailClosed: 'enabled',
        sharedAnalysisWaitFallback: 'enabled',
        distributedAnalysisLockSelfTest: 'enabled',
        mediaPublisherKit: 'enabled',
        campaignTaggedFixtureLinks: 'enabled',
        mediaCopyGenerator: 'enabled',
        adminPublisherOnly: 'enabled',
        mediaPublisherSelfTest: 'enabled',
        mediaCampaignControlRoom: 'enabled',
        contentLevelMediaAttribution: 'enabled',
        mediaCampaignConversion: 'enabled',
        publisherOutcomeTracking: 'enabled',
        mediaCampaignControlSelfTest: 'enabled',
        telegramNewsConversionEngine: 'enabled',
        newsPerItemAiCta: 'enabled',
        newsTeamIntentResolution: 'enabled',
        newsConversionTracking: 'enabled',
        newsConversionSelfTest: 'enabled',
        smartNewsFixtureLinking: 'enabled',
        newsTimeRelevanceGuard: 'enabled',
        perNewsFixtureCta: 'enabled',
        newsImpactDeltaGuide: 'enabled',
        smartNewsLinkSelfTest: 'enabled',
        newsImpactDelta: 'enabled',
        preNewsSnapshotGuard: 'enabled',
        explicitNewsRecheck: 'enabled',
        newsImpactMateriality: 'enabled',
        newsImpactDeltaSelfTest: 'enabled',
        newsImpactDecisionCard: 'enabled',
        newsImpactActionRouting: 'enabled',
        newsImpactCausalityGuardUx: 'enabled',
        newsImpactDecisionAnalytics: 'enabled',
        newsImpactDecisionSelfTest: 'enabled',
        newsImpactActionTracking: 'enabled',
        newsImpactActionAttribution: 'enabled',
        newsImpactActionAnalytics: 'enabled',
        newsImpactActionSelfTest: 'enabled',
        newsImpactActionFunnel: 'enabled',
        newsImpactDecisionConversion: 'enabled',
        newsImpactActionBottleneck: 'enabled',
        newsImpactActionFunnelSelfTest: 'enabled',
        newsImpactFunnelConfidenceGuard: 'enabled',
        newsImpactWilsonInterval: 'enabled',
        newsImpactSampleGate: 'enabled',
        newsImpactFunnelConfidenceSelfTest: 'enabled',
        newsImpactFunnelTrend: 'enabled',
        newsImpactPeriodComparison: 'enabled',
        newsImpactTrendSignificanceGuard: 'enabled',
        newsImpactActionTrendSelfTest: 'enabled',
        newsImpactTemporalAttribution: 'enabled',
        newsImpactActionWindowGuard: 'enabled',
        newsImpactMaturityGuard: 'enabled',
        newsImpactBoundaryAttribution: 'enabled',
        newsImpactTemporalAttributionSelfTest: 'enabled',
        newsImpactActionOutcomeTracking: 'enabled',
        newsImpactOutcomeTemporalGuard: 'enabled',
        newsImpactOutcomeQualityAnalytics: 'enabled',
        newsImpactOutcomeMeaningGuard: 'enabled',
        newsImpactOutcomeQualitySelfTest: 'enabled',
        newsImpactOutcomeFailureTracking: 'enabled',
        newsImpactFailureTaxonomy: 'enabled',
        newsImpactRecoveryUx: 'enabled',
        newsImpactFailurePrivacyGuard: 'enabled',
        newsImpactFailureDiagnosticsSelfTest: 'enabled',
        newsImpactRecoveryAttemptTracking: 'enabled',
        newsImpactRecoveryEffectiveness: 'enabled',
        newsImpactRecoveryMaturityGuard: 'enabled',
        newsImpactRecoverySampleGuard: 'enabled',
        newsImpactRecoveryEffectivenessSelfTest: 'enabled',
        newsImpactRecoveryStrategyGuard: 'enabled',
        newsImpactAdaptiveRecovery: 'enabled',
        newsImpactFixedFallbackGuard: 'enabled',
        newsImpactRecoveryStrategyCache: 'enabled',
        newsImpactRecoveryStrategySelfTest: 'enabled',
        newsImpactRecoveryStrategyParity: 'enabled',
        newsImpactRecoveryStabilityGuard: 'enabled',
        newsImpactRecoveryStabilitySelfTest: 'enabled',
        newsImpactRecoveryDriftGuard: 'enabled',
        newsImpactRecoveryDriftAudit: 'enabled',
        newsImpactRecoveryDriftSelfTest: 'enabled',
        newsImpactRecoveryTransitionHistory: 'enabled',
        newsImpactRecoveryAdminAlerts: 'enabled',
        newsImpactRecoveryTransitionPrivacyGuard: 'enabled',
        newsImpactRecoveryTransitionSelfTest: 'enabled',
        newsImpactRecoveryIncidentCenter: 'enabled',
        newsImpactRecoveryIncidentLifecycle: 'enabled',
        newsImpactRecoveryIncidentPrivacyGuard: 'enabled',
        newsImpactRecoveryIncidentSelfTest: 'enabled',
        newsImpactRecoveryIncidentAcknowledgement: 'enabled',
        newsImpactRecoveryIncidentRunbook: 'enabled',
        newsImpactRecoveryIncidentAlertSuppression: 'enabled',
        newsImpactRecoveryIncidentAckPrivacyGuard: 'enabled',
        newsImpactRecoveryIncidentAckSelfTest: 'enabled',
        newsImpactRecoveryIncidentSlo: 'enabled',
        newsImpactRecoveryIncidentEscalation: 'enabled',
        newsImpactRecoveryIncidentLatencyMetrics: 'enabled',
        newsImpactRecoveryIncidentSloSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloDashboard: 'enabled',
        newsImpactRecoveryIncidentWeeklyTrend: 'enabled',
        newsImpactRecoveryIncidentRecurrence: 'enabled',
        newsImpactRecoveryIncidentSloDashboardSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachFeed: 'enabled',
        newsImpactRecoveryIncidentBreachDrilldown: 'enabled',
        newsImpactRecoveryIncidentBreachPrivacyGuard: 'enabled',
        newsImpactRecoveryIncidentSloBreachFeedSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachWatchlist: 'enabled',
        newsImpactRecoveryIncidentBreachAging: 'enabled',
        newsImpactRecoveryIncidentSloBreachWatchlistSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachTriage: 'enabled',
        newsImpactRecoveryIncidentBreachStageBuckets: 'enabled',
        newsImpactRecoveryIncidentSloBreachTriageSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachTriageTrend: 'enabled',
        newsImpactRecoveryIncidentTriageRecurrence: 'enabled',
        newsImpactRecoveryIncidentSloBreachTriageTrendSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachImpactRanking: 'enabled',
        newsImpactRecoveryIncidentOverdueContribution: 'enabled',
        newsImpactRecoveryIncidentSloBreachImpactRankingSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloBreachImpactTrend: 'enabled',
        newsImpactRecoveryIncidentWeeklyOverdueBurden: 'enabled',
        newsImpactRecoveryIncidentSloBreachImpactTrendSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloImpactConcentration: 'enabled',
        newsImpactRecoveryIncidentTopContributionShares: 'enabled',
        newsImpactRecoveryIncidentSloImpactConcentrationSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloImpactConcentrationTrend: 'enabled',
        newsImpactRecoveryIncidentWeeklyConcentrationShares: 'enabled',
        newsImpactRecoveryIncidentSloImpactConcentrationTrendSelfTest: 'enabled',
        newsImpactRecoveryIncidentSloImpactExecutiveSummary: 'enabled',
        newsImpactRecoveryIncidentSloImpactUnifiedView: 'enabled',
        newsImpactRecoveryIncidentSloImpactExecutiveSummarySelfTest: 'enabled',
        newsImpactRecoveryIncidentSloImpactFocusQueue: 'enabled',
        newsImpactRecoveryIncidentSloImpactFocusOrdering: 'enabled',
        newsImpactRecoveryIncidentSloImpactFocusQueueSelfTest: 'enabled',
      });
    }
    if (url.pathname === '/api/app-manifest') return json({ version: '6.27.0-rc35', releaseCandidate: 'RC35' });
    if (url.pathname === '/api/public-status') return json({
      ok:true,
      status:'operational',
      version:'6.27.0-rc35',
      releaseCandidate:'RC35',
      services:{
        telegram:'operational',
        miniApp:'operational',
        aiAnalysis:'operational',
        search:'operational',
        live:'operational',
        ...serviceOverrides,
      },
    });
    if (['/privacy.html','/terms.html','/status.html'].includes(url.pathname)) return new Response('<!doctype html>', { status:200, headers:{
      'content-type':'text/html; charset=UTF-8',
      'content-security-policy':"default-src 'self'; object-src 'none'",
    }});
    if (url.pathname === '/telegram/webhook') return json({ ok:false },403);
    if (url.pathname === '/') return new Response('<!doctype html>', { status: 200, headers: {
      'content-type': 'text/html; charset=UTF-8',
      'content-security-policy': "default-src 'self'; script-src 'self' https://telegram.org; object-src 'none'",
      'x-content-type-options': 'nosniff',
    } });
    if (url.pathname === '/health/supabase') return json({ error: 'not found' }, 404);
    if (url.pathname.startsWith('/api/')) return json({ error: 'Telegram auth required' }, 401);
    return json({ error: 'not found' }, 404);
  };
}

test('post-deploy smoke validates RC35, security headers and protected routes', async () => {
  const result = await runDeploymentSmoke('https://football.example.test', '6.27.0-rc35', {
    fetchImpl: healthyFetch(),
    retries: 1,
    retryDelayMs: 0,
  });
  assert.equal(result.ok, true);
  assert.equal(result.checks, 25);
});

test('post-deploy smoke retries while the previous Worker version is propagating', async () => {
  const result = await runDeploymentSmoke('https://football.example.test/', '6.27.0-rc35', {
    fetchImpl: healthyFetch({ staleOnce: true }),
    retries: 2,
    retryDelayMs: 0,
  });
  assert.equal(result.version, '6.27.0-rc35');
});

test('post-deploy smoke rejects DEV_MODE in production', async () => {
  await assert.rejects(
    runDeploymentSmoke('https://football.example.test', '6.27.0-rc35', {
      fetchImpl: healthyFetch({ devMode: true }),
      retries: 1,
      retryDelayMs: 0,
    }),
    /DEV_MODE=true/,
  );
});


test('post-deploy smoke rejects enabled monetization before closed beta', async () => {
  await assert.rejects(
    runDeploymentSmoke('https://football.example.test', '6.27.0-rc35', {
      fetchImpl: healthyFetch({ monetization: 'enabled' }),
      retries: 1,
      retryDelayMs: 0,
    }),
    /MONETIZATION_ENABLED=false/,
  );
});

test('post-deploy smoke requires API-Football-backed public services to be operational', async () => {
  await assert.rejects(
    runDeploymentSmoke('https://football.example.test', '6.27.0-rc35', {
      fetchImpl: healthyFetch({ serviceOverrides: { aiAnalysis: 'configuration_required' } }),
      retries: 1,
      retryDelayMs: 0,
    }),
    /aiAnalysis must be operational/,
  );
});
