-- Football Analytics v6.5 / RC13
-- Settlement Finality Verification & Drift Guard.

alter table public.model_predictions
  add column if not exists settlement_verification_state text not null default 'unverified';

alter table public.model_predictions
  add column if not exists settlement_verified_at timestamptz;

alter table public.model_predictions
  add column if not exists settlement_verified_status text;

alter table public.model_predictions
  drop constraint if exists model_predictions_settlement_verification_state_check;

alter table public.model_predictions
  add constraint model_predictions_settlement_verification_state_check
  check (settlement_verification_state in ('unverified', 'verified', 'drift'));

create index if not exists model_predictions_settlement_finality_idx
  on public.model_predictions (settlement_verification_state, kickoff_at desc)
  where status = 'settled';

create table if not exists public.settlement_verification_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  fixture_id bigint not null,
  state text not null default 'drift',
  reason text not null default '',
  stored_home_goals integer,
  stored_away_goals integer,
  stored_outcome text not null default '',
  provider_home_goals integer,
  provider_away_goals integer,
  provider_outcome text not null default '',
  provider_status text not null default '',
  detail jsonb not null default '{}'::jsonb,
  constraint settlement_verification_events_state_check
    check (state in ('drift'))
);

alter table public.settlement_verification_events enable row level security;

create index if not exists settlement_verification_events_fixture_idx
  on public.settlement_verification_events (fixture_id, observed_at desc);

create index if not exists settlement_verification_events_observed_idx
  on public.settlement_verification_events (observed_at desc);

comment on column public.model_predictions.settlement_verification_state is
  'RC13 post-settlement finality state. Drift rows are excluded from model-quality/calibration until reviewed.';

comment on table public.settlement_verification_events is
  'RC13 immutable audit of provider final-result drift. Service-role backend only; stored prediction outcomes are not silently rewritten.';
