-- Football Analytics v6.10 / RC18
-- Atomic calibration transitions, manual freeze controls, immutable audit,
-- and remediation of the RC16 validation-table RLS gap.

alter table public.model_calibration_state
  add column if not exists frozen boolean not null default false,
  add column if not exists freeze_reason text,
  add column if not exists frozen_at timestamptz,
  add column if not exists frozen_by bigint,
  add column if not exists last_transition text,
  add column if not exists last_transition_reason text;

create table if not exists public.model_calibration_transitions (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('initialize','promote','rollback','manual_rollback','freeze','unfreeze')),
  from_active_fingerprint text,
  to_active_fingerprint text,
  from_previous_fingerprint text,
  to_previous_fingerprint text,
  expected_revision integer not null check (expected_revision >= 0),
  resulting_revision integer not null check (resulting_revision > expected_revision),
  reason text not null,
  actor_telegram_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists model_calibration_transitions_created_idx
  on public.model_calibration_transitions (created_at desc);

alter table public.model_calibration_validations enable row level security;
alter table public.model_calibration_profiles enable row level security;
alter table public.model_calibration_state enable row level security;
alter table public.model_calibration_transitions enable row level security;

revoke all on table public.model_calibration_validations from anon, authenticated;
revoke all on table public.model_calibration_profiles from anon, authenticated;
revoke all on table public.model_calibration_state from anon, authenticated;
revoke all on table public.model_calibration_transitions from anon, authenticated;

grant select, insert, update, delete on table public.model_calibration_validations to service_role;
grant select, insert, update, delete on table public.model_calibration_profiles to service_role;
grant select, insert, update, delete on table public.model_calibration_state to service_role;
grant select, insert on table public.model_calibration_transitions to service_role;
grant usage, select on sequence public.model_calibration_transitions_id_seq to service_role;

create or replace function public.transition_model_calibration(
  p_expected_revision integer,
  p_action text,
  p_target_fingerprint text default null,
  p_reason text default '',
  p_actor_telegram_id bigint default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_state public.model_calibration_state%rowtype;
  v_action text := lower(trim(coalesce(p_action, '')));
  v_reason text := left(trim(coalesce(p_reason, '')), 500);
  v_target text := nullif(trim(coalesce(p_target_fingerprint, '')), '');
  v_from_active text;
  v_from_previous text;
  v_to_active text;
  v_to_previous text;
  v_now timestamptz := now();
begin
  if coalesce(p_expected_revision, -1) < 0 then
    raise exception using errcode = '22023', message = 'expected revision must be non-negative';
  end if;
  if v_action not in ('initialize','promote','rollback','manual_rollback','freeze','unfreeze') then
    raise exception using errcode = '22023', message = 'unsupported calibration transition';
  end if;
  if length(v_reason) < 3 then
    raise exception using errcode = '22023', message = 'transition reason is required';
  end if;

  select * into v_state
  from public.model_calibration_state
  where id = 'global'
  for update;

  if not found then
    insert into public.model_calibration_state (id) values ('global')
    on conflict (id) do nothing;
    select * into v_state
    from public.model_calibration_state
    where id = 'global'
    for update;
  end if;

  if v_state.revision <> p_expected_revision then
    raise exception using
      errcode = '40001',
      message = format('calibration revision conflict: expected %s, current %s', p_expected_revision, v_state.revision);
  end if;

  if v_state.frozen and v_action not in ('unfreeze','manual_rollback') then
    raise exception using errcode = '55000', message = 'calibration lifecycle is frozen';
  end if;

  v_from_active := v_state.active_fingerprint;
  v_from_previous := v_state.previous_fingerprint;
  v_to_active := v_from_active;
  v_to_previous := v_from_previous;

  if v_action in ('initialize','promote','rollback','manual_rollback') then
    if v_action in ('rollback','manual_rollback') and v_target is null then
      v_target := v_state.previous_fingerprint;
    end if;
    if v_target is null or not exists (
      select 1 from public.model_calibration_profiles where fingerprint = v_target
    ) then
      raise exception using errcode = '23503', message = 'target calibration profile does not exist';
    end if;
  end if;

  case v_action
    when 'initialize' then
      if v_state.active_fingerprint is not null then
        raise exception using errcode = '55000', message = 'calibration lifecycle is already initialized';
      end if;
      v_to_active := v_target;
      v_to_previous := null;
      update public.model_calibration_profiles
      set status = 'active', activated_at = v_now, retired_at = null, rollback_reason = null, updated_at = v_now
      where fingerprint = v_target;

    when 'promote' then
      if v_target = v_state.active_fingerprint then
        raise exception using errcode = '55000', message = 'target profile is already active';
      end if;
      v_to_active := v_target;
      v_to_previous := v_state.active_fingerprint;
      update public.model_calibration_profiles
      set status = 'retired', retired_at = v_now, updated_at = v_now
      where fingerprint = v_state.active_fingerprint;
      update public.model_calibration_profiles
      set status = 'active', activated_at = v_now, retired_at = null, rollback_reason = null, updated_at = v_now
      where fingerprint = v_target;

    when 'rollback' then
      if v_state.previous_fingerprint is null or v_target <> v_state.previous_fingerprint then
        raise exception using errcode = '55000', message = 'automatic rollback target must be the previous champion';
      end if;
      v_to_active := v_target;
      v_to_previous := null;
      update public.model_calibration_profiles
      set status = 'rolled_back', retired_at = v_now, rollback_reason = v_reason, updated_at = v_now
      where fingerprint = v_state.active_fingerprint;
      update public.model_calibration_profiles
      set status = 'active', activated_at = v_now, retired_at = null, rollback_reason = null, updated_at = v_now
      where fingerprint = v_target;

    when 'manual_rollback' then
      if v_state.previous_fingerprint is null or v_target <> v_state.previous_fingerprint then
        raise exception using errcode = '55000', message = 'manual rollback target must be the previous champion';
      end if;
      v_to_active := v_target;
      v_to_previous := null;
      update public.model_calibration_profiles
      set status = 'rolled_back', retired_at = v_now, rollback_reason = v_reason, updated_at = v_now
      where fingerprint = v_state.active_fingerprint;
      update public.model_calibration_profiles
      set status = 'active', activated_at = v_now, retired_at = null, rollback_reason = null, updated_at = v_now
      where fingerprint = v_target;

    when 'freeze' then
      if v_state.frozen then
        raise exception using errcode = '55000', message = 'calibration lifecycle is already frozen';
      end if;

    when 'unfreeze' then
      if not v_state.frozen then
        raise exception using errcode = '55000', message = 'calibration lifecycle is not frozen';
      end if;
  end case;

  update public.model_calibration_state
  set active_fingerprint = v_to_active,
      previous_fingerprint = v_to_previous,
      activated_at = case when v_action in ('initialize','promote','rollback','manual_rollback') then v_now else activated_at end,
      last_evaluated_at = v_now,
      last_rollback_at = case when v_action in ('rollback','manual_rollback') then v_now else last_rollback_at end,
      frozen = case when v_action = 'freeze' then true when v_action = 'unfreeze' then false else frozen end,
      freeze_reason = case when v_action = 'freeze' then v_reason when v_action = 'unfreeze' then null else freeze_reason end,
      frozen_at = case when v_action = 'freeze' then v_now when v_action = 'unfreeze' then null else frozen_at end,
      frozen_by = case when v_action = 'freeze' then p_actor_telegram_id when v_action = 'unfreeze' then null else frozen_by end,
      last_transition = v_action,
      last_transition_reason = v_reason,
      revision = revision + 1,
      updated_at = v_now
  where id = 'global'
  returning * into v_state;

  insert into public.model_calibration_transitions (
    action, from_active_fingerprint, to_active_fingerprint,
    from_previous_fingerprint, to_previous_fingerprint,
    expected_revision, resulting_revision, reason, actor_telegram_id, metadata, created_at
  ) values (
    v_action, v_from_active, v_to_active,
    v_from_previous, v_to_previous,
    p_expected_revision, v_state.revision, v_reason, p_actor_telegram_id,
    coalesce(p_metadata, '{}'::jsonb), v_now
  );

  return jsonb_build_object(
    'id', v_state.id,
    'active_fingerprint', v_state.active_fingerprint,
    'previous_fingerprint', v_state.previous_fingerprint,
    'activated_at', v_state.activated_at,
    'last_evaluated_at', v_state.last_evaluated_at,
    'last_rollback_at', v_state.last_rollback_at,
    'frozen', v_state.frozen,
    'freeze_reason', v_state.freeze_reason,
    'frozen_at', v_state.frozen_at,
    'revision', v_state.revision,
    'last_transition', v_state.last_transition,
    'last_transition_reason', v_state.last_transition_reason,
    'updated_at', v_state.updated_at
  );
end;
$$;

revoke all on function public.transition_model_calibration(integer, text, text, text, bigint, jsonb) from public, anon, authenticated;
grant execute on function public.transition_model_calibration(integer, text, text, text, bigint, jsonb) to service_role;

comment on function public.transition_model_calibration(integer, text, text, text, bigint, jsonb) is
  'RC18 atomic compare-and-swap transition for the singleton calibration lifecycle. Callable only by the backend service role.';

comment on table public.model_calibration_transitions is
  'RC18 immutable audit for calibration initialization, promotion, rollback, freeze and unfreeze transitions.';

notify pgrst, 'reload schema';
