-- Football Analytics v6.1
-- Prediction Integrity Remediation audit trail
-- Run once AFTER supabase_migration_v3_7.sql.

create table if not exists public.prediction_integrity_actions (
  id bigint generated by default as identity primary key,
  action_id uuid not null unique,
  created_at timestamptz not null default now(),
  action_type text not null default 'recover'
    check (action_type in ('dry_run','recover')),
  status text not null default 'completed'
    check (status in ('completed','partial','failed')),
  reason text not null default '',
  admin_telegram_id bigint,
  candidate_count integer not null default 0,
  inspected_count integer not null default 0,
  settled_count integer not null default 0,
  skipped_count integer not null default 0,
  fixture_ids jsonb not null default '[]'::jsonb,
  detail jsonb not null default '{}'::jsonb
);

create index if not exists prediction_integrity_actions_created_idx
  on public.prediction_integrity_actions(created_at desc);

create index if not exists prediction_integrity_actions_status_idx
  on public.prediction_integrity_actions(status, created_at desc);

alter table public.prediction_integrity_actions enable row level security;

comment on table public.prediction_integrity_actions is
  'Auditable admin-triggered recovery attempts for stale pending model predictions. Written and read only by the backend service role.';

comment on column public.prediction_integrity_actions.admin_telegram_id is
  'Internal audit actor. Never exposed by the public/admin remediation response.';
