-- Football Analytics v6.9 / RC17 fresh-install baseline.
-- Use ONLY for a new Supabase project. Existing installations must apply the
-- numbered migrations in order and finish with supabase_migration_v6_9.sql.

create table if not exists public.users (
  telegram_id bigint primary key,
  username text,
  first_name text,
  last_name text,
  photo_url text,
  plan text not null default 'FREE' check (plan in ('FREE','PRO','PREMIUM')),
  subscription_until timestamptz,
  subscription_canceled boolean not null default false,
  telegram_payment_charge_id text,
  plan_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_daily (
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  usage_date date not null,
  analyses integer not null default 0 check (analyses >= 0),
  updated_at timestamptz not null default now(),
  primary key (telegram_id, usage_date)
);

create table if not exists public.analysis_cache (
  cache_key text primary key,
  fixture_id bigint not null default 0,
  payload jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists analysis_cache_expires_at_idx on public.analysis_cache(expires_at);

create table if not exists public.analysis_history (
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  fixture_id bigint not null,
  home_name text not null default '',
  away_name text not null default '',
  league_name text not null default '',
  fixture_date timestamptz,
  home_logo text,
  away_logo text,
  viewed_at timestamptz not null default now(),
  primary key (telegram_id, fixture_id)
);
create index if not exists analysis_history_user_viewed_idx on public.analysis_history(telegram_id, viewed_at desc);

create table if not exists public.favorites (
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  team_id bigint not null,
  team_name text not null,
  team_logo text not null default '',
  created_at timestamptz not null default now(),
  primary key (telegram_id, team_id)
);

create table if not exists public.user_preferences (
  telegram_id bigint primary key references public.users(telegram_id) on delete cascade,
  default_filter text not null default 'top' check (default_filter in ('top','favorites','all')),
  reminder_minutes integer not null default 30 check (reminder_minutes in (15,30,60)),
  kickoff_notification boolean not null default true,
  hide_youth boolean not null default true,
  favorite_first boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.match_reminders (
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  fixture_id bigint not null,
  home_name text not null,
  away_name text not null,
  league_name text not null default '',
  fixture_date timestamptz not null,
  enabled boolean not null default true,
  remind_before_minutes integer not null default 30 check (remind_before_minutes in (15,30,60)),
  kickoff_notify boolean not null default true,
  notified_at timestamptz,
  kickoff_notified_at timestamptz,
  prematch_claimed_at timestamptz,
  kickoff_claimed_at timestamptz,
  prematch_attempts integer not null default 0,
  kickoff_attempts integer not null default 0,
  delivery_last_error text,
  delivery_last_attempt_at timestamptz,
  delivery_last_success_at timestamptz,
  delivery_disabled_reason text,
  delivery_retry_after timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (telegram_id, fixture_id)
);
create index if not exists match_reminders_due_idx on public.match_reminders(enabled, fixture_date);

create table if not exists public.runtime_controls (
  id text primary key default 'global' check (id = 'global'),
  maintenance_mode boolean not null default false,
  analysis_enabled boolean not null default true,
  search_enabled boolean not null default true,
  live_enabled boolean not null default true,
  reminders_enabled boolean not null default true,
  expanded_data_enabled boolean not null default true,
  auto_settlement_recovery_enabled boolean not null default false,
  message text not null default '',
  revision integer not null default 1 check (revision > 0),
  updated_at timestamptz not null default now(),
  updated_by bigint
);
insert into public.runtime_controls (id) values ('global') on conflict (id) do nothing;

create table if not exists public.runtime_control_history (
  id bigint generated by default as identity primary key,
  revision integer not null unique,
  action text not null,
  reason text not null default '',
  snapshot jsonb not null,
  app_version text not null,
  changed_by bigint,
  source_revision integer,
  created_at timestamptz not null default now()
);

create table if not exists public.model_predictions (
  fixture_id bigint primary key,
  analysis_version text not null,
  captured_at timestamptz not null,
  kickoff_at timestamptz not null,
  league_id bigint,
  league_name text not null default '',
  home_id bigint,
  away_id bigint,
  home_name text not null default '',
  away_name text not null default '',
  home_prob double precision not null,
  draw_prob double precision not null,
  away_prob double precision not null,
  predicted_outcome text not null check (predicted_outcome in ('home','draw','away')),
  confidence_score double precision,
  signal_names text[] not null default '{}',
  signal_weights jsonb not null default '{}'::jsonb,
  signal_probabilities jsonb not null default '{}'::jsonb,
  raw_home_prob double precision,
  raw_draw_prob double precision,
  raw_away_prob double precision,
  calibration_mode text not null default 'baseline',
  calibration_profile_fingerprint text,
  calibration_temperature double precision not null default 1,
  calibration_sample integer not null default 0,
  calibration_weights jsonb not null default '{}'::jsonb,
  data_mode text not null default '',
  completeness_score integer not null default 0,
  completeness_max integer not null default 0,
  home_expected_goals double precision,
  away_expected_goals double precision,
  over25_prob double precision,
  btts_prob double precision,
  status text not null default 'pending' check (status in ('pending','settled','void')),
  settled_at timestamptz,
  actual_home_goals integer,
  actual_away_goals integer,
  actual_outcome text check (actual_outcome is null or actual_outcome in ('home','draw','away')),
  correct boolean,
  brier_score double precision,
  over25_actual boolean,
  over25_correct boolean,
  btts_actual boolean,
  btts_correct boolean,
  settlement_verification_state text not null default 'unverified'
    check (settlement_verification_state in ('unverified','verified','confirmed','drift','adjudicated')),
  settlement_verified_at timestamptz,
  settlement_verified_status text,
  settlement_verification_count integer not null default 0 check (settlement_verification_count between 0 and 2),
  settlement_first_verified_at timestamptz,
  settlement_resolved_at timestamptz,
  settlement_resolution_action text check (settlement_resolution_action is null or settlement_resolution_action in ('keep_stored','accept_provider','void_prediction')),
  settlement_resolution_event_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists model_predictions_status_kickoff_idx on public.model_predictions(status, kickoff_at desc);
create index if not exists model_predictions_finality_idx on public.model_predictions(settlement_verification_state, kickoff_at desc) where status = 'settled';
create index if not exists model_predictions_calibration_profile_idx on public.model_predictions(calibration_profile_fingerprint, kickoff_at desc) where calibration_profile_fingerprint is not null;

create table if not exists public.model_calibration_validations (
  candidate_fingerprint text primary key,
  created_at timestamptz not null default now(),
  profile_version text not null,
  decision text not null check (decision in ('baseline','shadow','held','promoted')),
  trusted_sample integer not null default 0,
  train_sample integer not null default 0,
  validation_sample integer not null default 0,
  temperature_candidate double precision,
  temperature_active boolean not null default false,
  candidate_weights jsonb not null default '{}'::jsonb,
  weights_active boolean not null default false,
  baseline_brier double precision,
  candidate_brier double precision,
  baseline_log_loss double precision,
  candidate_log_loss double precision,
  brier_gain double precision,
  log_loss_gain double precision,
  detail jsonb not null default '{}'::jsonb
);

create table if not exists public.model_calibration_profiles (
  fingerprint text primary key,
  profile_version text not null,
  status text not null default 'challenger' check (status in ('baseline','challenger','held','active','retired','rolled_back')),
  temperature double precision not null default 1 check (temperature between 0.8 and 1.35),
  temperature_active boolean not null default false,
  signal_weights jsonb not null default '{}'::jsonb,
  weights_active boolean not null default false,
  trusted_sample integer not null default 0,
  train_sample integer not null default 0,
  validation_sample integer not null default 0,
  validation_windows jsonb not null default '[]'::jsonb,
  baseline_brier double precision,
  candidate_brier double precision,
  baseline_log_loss double precision,
  candidate_log_loss double precision,
  source_cutoff timestamptz,
  activated_at timestamptz,
  retired_at timestamptz,
  rollback_reason text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists model_calibration_profiles_status_idx on public.model_calibration_profiles(status, created_at desc);

create table if not exists public.model_calibration_state (
  id text primary key default 'global' check (id = 'global'),
  active_fingerprint text references public.model_calibration_profiles(fingerprint) on delete restrict,
  previous_fingerprint text references public.model_calibration_profiles(fingerprint) on delete restrict,
  activated_at timestamptz,
  last_evaluated_at timestamptz,
  last_rollback_at timestamptz,
  revision integer not null default 0,
  updated_at timestamptz not null default now(),
  check (active_fingerprint is null or active_fingerprint is distinct from previous_fingerprint)
);
create index if not exists model_calibration_state_active_idx on public.model_calibration_state(active_fingerprint) where active_fingerprint is not null;
create index if not exists model_calibration_state_previous_idx on public.model_calibration_state(previous_fingerprint) where previous_fingerprint is not null;
insert into public.model_calibration_state (id) values ('global') on conflict (id) do nothing;

create table if not exists public.prediction_integrity_actions (
  action_id uuid primary key,
  action_type text not null check (action_type in ('dry_run','recover','auto_recover','circuit_reset')),
  trigger_source text not null default 'admin',
  status text not null check (status in ('started','completed','partial','failed','interrupted')),
  reason text not null default '',
  admin_telegram_id bigint,
  candidate_count integer not null default 0,
  inspected_count integer not null default 0,
  settled_count integer not null default 0,
  skipped_count integer not null default 0,
  fixture_ids bigint[] not null default '{}',
  detail jsonb not null default '{}'::jsonb,
  attempt_no integer not null default 1 check (attempt_no between 1 and 3),
  retry_of_action_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists prediction_integrity_actions_created_idx on public.prediction_integrity_actions(created_at desc);

create table if not exists public.settlement_watchdog_state (
  id text primary key default 'global' check (id = 'global'),
  consecutive_failures integer not null default 0,
  circuit_open_until timestamptz,
  last_run_at timestamptz,
  last_status text not null default 'never',
  last_action_id text,
  last_error text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.settlement_watchdog_state(id) values ('global') on conflict (id) do nothing;

create table if not exists public.settlement_verification_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  fixture_id bigint not null,
  state text not null default 'drift' check (state = 'drift'),
  reason text not null default '',
  stored_home_goals integer,
  stored_away_goals integer,
  stored_outcome text not null default '',
  provider_home_goals integer,
  provider_away_goals integer,
  provider_outcome text not null default '',
  provider_status text not null default '',
  detail jsonb not null default '{}'::jsonb
);
create index if not exists settlement_verification_events_fixture_idx on public.settlement_verification_events(fixture_id, observed_at desc);

create table if not exists public.settlement_drift_resolutions (
  source_event_id bigint primary key references public.settlement_verification_events(id) on delete restrict,
  fixture_id bigint not null,
  action text not null check (action in ('keep_stored','accept_provider','void_prediction')),
  reason text not null,
  admin_telegram_id bigint,
  before_snapshot jsonb not null default '{}'::jsonb,
  provider_snapshot jsonb not null default '{}'::jsonb,
  after_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ops_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  severity text not null check (severity in ('info','warning','error','critical')),
  source text not null,
  event_type text not null,
  code text not null default '',
  message text not null default '',
  endpoint text not null default '',
  status integer,
  duration_ms integer,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists ops_events_created_idx on public.ops_events(created_at desc);

create table if not exists public.match_integrity_runs (
  run_id uuid primary key,
  observed_at timestamptz not null,
  fixture_date date,
  inspected integer not null default 0,
  accepted integer not null default 0,
  clean integer not null default 0,
  incomplete integer not null default 0,
  warning_matches integer not null default 0,
  quarantined integer not null default 0,
  duplicates integer not null default 0,
  repaired integer not null default 0,
  warning_count integer not null default 0,
  error_count integer not null default 0,
  quality_score double precision not null default 0,
  health text not null default 'ok',
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.match_integrity_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.match_integrity_runs(run_id) on delete cascade,
  observed_at timestamptz not null,
  fixture_date date,
  fixture_id bigint,
  severity text not null,
  issue_code text not null,
  message text not null,
  home_name text not null default '',
  away_name text not null default '',
  league_name text not null default '',
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists match_integrity_events_observed_idx on public.match_integrity_events(observed_at desc);
create index if not exists match_integrity_events_run_idx on public.match_integrity_events(run_id) where run_id is not null;

create table if not exists public.odds_snapshots (
  fixture_id bigint not null,
  market text not null,
  snapshot_time timestamptz not null,
  home_odd double precision not null,
  draw_odd double precision not null,
  away_odd double precision not null,
  home_prob double precision not null,
  draw_prob double precision not null,
  away_prob double precision not null,
  source_count integer not null default 0,
  primary key (fixture_id, market, snapshot_time)
);

create table if not exists public.billing_payments (
  telegram_payment_charge_id text primary key,
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  plan text not null check (plan in ('PRO','PREMIUM')),
  stars_amount integer not null,
  currency text not null default 'XTR',
  invoice_payload text not null,
  provider_payment_charge_id text,
  subscription_expiration_date timestamptz,
  is_recurring boolean not null default false,
  is_first_recurring boolean not null default false,
  status text not null default 'paid',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists billing_payments_user_idx on public.billing_payments(telegram_id, created_at desc);

-- All data is accessed by the Worker with a Supabase secret/service-role key.
-- The Telegram client never receives database credentials.
do $$
declare table_name text;
begin
  foreach table_name in array array[
    'users','usage_daily','analysis_cache','analysis_history','favorites','user_preferences','match_reminders',
    'runtime_controls','runtime_control_history','model_predictions','model_calibration_validations',
    'model_calibration_profiles','model_calibration_state','prediction_integrity_actions','settlement_watchdog_state',
    'settlement_verification_events','settlement_drift_resolutions','ops_events','match_integrity_runs',
    'match_integrity_events','odds_snapshots','billing_payments'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end $$;

grant usage, select on all sequences in schema public to service_role;
