-- MatchRadar v6.25 / Match Pass, Day Pass, Weekend Pass
-- Additive server-side entitlement storage and atomic activation/consumption.
-- Subscription billing remains in public.billing_payments; Pass purchases reuse the
-- same Telegram Stars webhook/invoice transport but persist access in this entitlement ledger.

create table if not exists public.user_entitlements (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  entitlement_type text not null
    check (entitlement_type in ('MATCH_PASS','DAY_PASS','WEEKEND_PASS')),
  fixture_id bigint,
  starts_at timestamptz not null,
  expires_at timestamptz not null,
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  usage_count integer not null default 0 check (usage_count >= 0),
  stars_amount integer not null check (stars_amount > 0),
  payment_charge_id text not null unique check (char_length(payment_charge_id) between 1 and 240),
  invoice_payload text not null check (char_length(invoice_payload) between 1 and 512),
  status text not null default 'active'
    check (status in ('active','refunded','canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at > starts_at),
  check (
    (entitlement_type = 'MATCH_PASS' and fixture_id is not null and fixture_id > 0)
    or (entitlement_type in ('DAY_PASS','WEEKEND_PASS') and fixture_id is null)
  )
);

create index if not exists user_entitlements_user_expiry_idx
  on public.user_entitlements (telegram_id, expires_at desc);

create index if not exists user_entitlements_fixture_idx
  on public.user_entitlements (telegram_id, fixture_id, expires_at desc)
  where fixture_id is not null;

alter table public.user_entitlements enable row level security;
revoke all privileges on table public.user_entitlements from public, anon, authenticated;
grant select, insert, update, delete on table public.user_entitlements to service_role;
grant usage, select on sequence public.user_entitlements_id_seq to service_role;

comment on table public.user_entitlements is
  'Server-only temporary access grants created from verified Telegram Stars Pass purchases.';

create or replace function public.activate_pass_entitlement(
  p_telegram_id bigint,
  p_entitlement_type text,
  p_fixture_id bigint,
  p_starts_at timestamptz,
  p_expires_at timestamptz,
  p_usage_limit integer,
  p_stars_amount integer,
  p_payment_charge_id text,
  p_invoice_payload text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_existing public.user_entitlements%rowtype;
  v_id bigint;
  v_type text := upper(btrim(coalesce(p_entitlement_type, '')));
  v_charge text := btrim(coalesce(p_payment_charge_id, ''));
  v_payload text := coalesce(p_invoice_payload, '');
begin
  if p_telegram_id is null or p_telegram_id <= 0
     or v_type not in ('MATCH_PASS','DAY_PASS','WEEKEND_PASS')
     or p_starts_at is null or p_expires_at is null or p_expires_at <= p_starts_at
     or p_stars_amount is null or p_stars_amount <= 0
     or (p_usage_limit is not null and p_usage_limit <= 0)
     or (v_type = 'WEEKEND_PASS' and p_usage_limit is null)
     or (v_type in ('MATCH_PASS','DAY_PASS') and p_usage_limit is not null)
     or v_charge = '' or char_length(v_charge) > 240
     or v_payload = '' or char_length(v_payload) > 512
     or (v_type = 'MATCH_PASS' and (p_fixture_id is null or p_fixture_id <= 0))
     or (v_type in ('DAY_PASS','WEEKEND_PASS') and p_fixture_id is not null) then
    return jsonb_build_object('activated', false, 'duplicate', false, 'reason', 'invalid_input');
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('matchradar:pass-entitlement'),
    pg_catalog.hashtext(v_charge)
  );

  select *
  into v_existing
  from public.user_entitlements
  where payment_charge_id = v_charge
  for update;

  if found then
    if v_existing.telegram_id = p_telegram_id
       and v_existing.entitlement_type = v_type
       and coalesce(v_existing.fixture_id, 0) = coalesce(p_fixture_id, 0)
       and coalesce(v_existing.usage_limit, 0) = coalesce(p_usage_limit, 0)
       and v_existing.stars_amount = p_stars_amount
       and v_existing.invoice_payload = v_payload then
      return jsonb_build_object(
        'activated', false,
        'duplicate', true,
        'reason', 'duplicate',
        'entitlementId', v_existing.id,
        'startsAt', v_existing.starts_at,
        'expiresAt', v_existing.expires_at
      );
    end if;
    return jsonb_build_object(
      'activated', false,
      'duplicate', false,
      'reason', 'payment_charge_conflict',
      'entitlementId', v_existing.id
    );
  end if;

  insert into public.user_entitlements (
    telegram_id,
    entitlement_type,
    fixture_id,
    starts_at,
    expires_at,
    usage_limit,
    usage_count,
    stars_amount,
    payment_charge_id,
    invoice_payload,
    status,
    created_at,
    updated_at
  ) values (
    p_telegram_id,
    v_type,
    p_fixture_id,
    p_starts_at,
    p_expires_at,
    p_usage_limit,
    0,
    p_stars_amount,
    v_charge,
    v_payload,
    'active',
    p_starts_at,
    p_starts_at
  )
  returning id into v_id;

  return jsonb_build_object(
    'activated', true,
    'duplicate', false,
    'reason', 'created',
    'entitlementId', v_id,
    'startsAt', p_starts_at,
    'expiresAt', p_expires_at
  );
end;
$$;

create or replace function public.consume_pass_entitlement(
  p_telegram_id bigint,
  p_entitlement_id bigint,
  p_fixture_id bigint default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_row public.user_entitlements%rowtype;
  v_now timestamptz := now();
begin
  if p_telegram_id is null or p_telegram_id <= 0
     or p_entitlement_id is null or p_entitlement_id <= 0 then
    return jsonb_build_object('allowed', false, 'reason', 'invalid_input');
  end if;

  select *
  into v_row
  from public.user_entitlements
  where id = p_entitlement_id
    and telegram_id = p_telegram_id
  for update;

  if not found then return jsonb_build_object('allowed', false, 'reason', 'not_found'); end if;
  if v_row.status <> 'active' then return jsonb_build_object('allowed', false, 'reason', v_row.status); end if;
  if v_row.starts_at > v_now then return jsonb_build_object('allowed', false, 'reason', 'not_started'); end if;
  if v_row.expires_at <= v_now then return jsonb_build_object('allowed', false, 'reason', 'expired'); end if;
  if v_row.entitlement_type = 'MATCH_PASS' and coalesce(p_fixture_id, 0) <> v_row.fixture_id then
    return jsonb_build_object('allowed', false, 'reason', 'fixture_mismatch');
  end if;
  if v_row.usage_limit is not null and v_row.usage_count >= v_row.usage_limit then
    return jsonb_build_object('allowed', false, 'reason', 'usage_exhausted');
  end if;

  if v_row.usage_limit is not null then
    update public.user_entitlements
    set usage_count = usage_count + 1,
        updated_at = v_now
    where id = v_row.id
    returning usage_count into v_row.usage_count;
  end if;

  return jsonb_build_object(
    'allowed', true,
    'reason', 'consumed',
    'entitlementId', v_row.id,
    'usageCount', v_row.usage_count,
    'usageLimit', v_row.usage_limit,
    'expiresAt', v_row.expires_at
  );
end;
$$;

create or replace function public.refund_pass_entitlement_usage(
  p_telegram_id bigint,
  p_entitlement_id bigint
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_count integer;
begin
  if p_telegram_id is null or p_telegram_id <= 0
     or p_entitlement_id is null or p_entitlement_id <= 0 then
    return jsonb_build_object('updated', false, 'reason', 'invalid_input');
  end if;

  update public.user_entitlements
  set usage_count = greatest(0, usage_count - 1),
      updated_at = now()
  where id = p_entitlement_id
    and telegram_id = p_telegram_id
    and usage_limit is not null
    and usage_count > 0
  returning usage_count into v_count;

  if v_count is null then
    return jsonb_build_object('updated', false, 'reason', 'not_refundable');
  end if;

  return jsonb_build_object(
    'updated', true,
    'reason', 'refunded',
    'entitlementId', p_entitlement_id,
    'usageCount', v_count
  );
end;
$$;

create or replace function public.refund_pass_entitlement(
  p_telegram_id bigint,
  p_payment_charge_id text
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_id bigint;
begin
  update public.user_entitlements
  set status = 'refunded',
      updated_at = now()
  where telegram_id = p_telegram_id
    and payment_charge_id = btrim(coalesce(p_payment_charge_id, ''))
    and status = 'active'
  returning id into v_id;

  if v_id is null then
    return jsonb_build_object('updated', false, 'reason', 'not_found');
  end if;
  return jsonb_build_object('updated', true, 'reason', 'refunded', 'entitlementId', v_id);
end;
$$;

revoke execute on function public.activate_pass_entitlement(bigint,text,bigint,timestamptz,timestamptz,integer,integer,text,text)
  from public, anon, authenticated;
grant execute on function public.activate_pass_entitlement(bigint,text,bigint,timestamptz,timestamptz,integer,integer,text,text)
  to service_role;

revoke execute on function public.consume_pass_entitlement(bigint,bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.consume_pass_entitlement(bigint,bigint,bigint)
  to service_role;

revoke execute on function public.refund_pass_entitlement_usage(bigint,bigint)
  from public, anon, authenticated;
grant execute on function public.refund_pass_entitlement_usage(bigint,bigint)
  to service_role;

revoke execute on function public.refund_pass_entitlement(bigint,text)
  from public, anon, authenticated;
grant execute on function public.refund_pass_entitlement(bigint,text)
  to service_role;

-- Preserve the established structural fingerprint while v6.25 additive objects
-- are verified explicitly by the Worker schema probe.
create or replace function public.backend_schema_fingerprint()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
with parts as (
  select
    'C|' || c.table_name || '|' || c.ordinal_position || '|' || c.column_name || '|' ||
    c.data_type || '|' || coalesce(c.udt_name,'') || '|' || c.is_nullable || '|' ||
    coalesce(c.column_default,'') as part
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name not in (
      'provider_incident_alert_deliveries',
      'analysis_timeline_snapshots',
      'favorite_players',
      'smart_notification_deliveries',
      'user_entitlements'
    )
    and not (
      (c.table_name = 'analysis_cache' and c.column_name in ('provider','source_updated_at','freshness_status','updated_at'))
      or (c.table_name = 'odds_snapshots' and c.column_name in ('provider','bookmaker_count','source_updated_at'))
      or (c.table_name = 'model_predictions' and c.column_name in ('data_provenance','model_inputs_version'))
      or (c.table_name = 'ops_events' and c.column_name = 'transition_key')
      or (c.table_name = 'user_preferences' and c.column_name = 'notification_preferences')
      or (c.table_name = 'match_reminders' and c.column_name in (
        'lineup_notified_at','lineup_claimed_at','lineup_attempts',
        'important_change_notified_at','important_change_claimed_at','important_change_attempts'
      ))
    )
  union all
  select
    'K|' || tc.table_name || '|' || tc.constraint_name || '|' || tc.constraint_type || '|' ||
    coalesce(pg_get_constraintdef(pc.oid, true),'')
  from information_schema.table_constraints tc
  join pg_constraint pc on pc.conname = tc.constraint_name
  join pg_namespace pn on pn.oid = pc.connamespace and pn.nspname = 'public'
  where tc.table_schema = 'public'
    and tc.table_name not in (
      'provider_incident_alert_deliveries',
      'analysis_timeline_snapshots',
      'favorite_players',
      'smart_notification_deliveries',
      'user_entitlements'
    )
    and tc.constraint_name <> 'user_preferences_notification_preferences_object_check'
    and not (tc.table_name = 'ops_events' and tc.constraint_name = 'ops_events_transition_key_key')
  union all
  select 'I|' || indexname || '|' || indexdef
  from pg_indexes
  where schemaname = 'public'
    and tablename not in (
      'provider_incident_alert_deliveries',
      'analysis_timeline_snapshots',
      'favorite_players',
      'smart_notification_deliveries',
      'user_entitlements'
    )
    and not (tablename = 'ops_events' and indexname = 'ops_events_transition_key_key')
  union all
  select
    'F|' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')|' ||
    pg_get_function_result(p.oid) || '|definer=' || p.prosecdef::text
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname not in (
      'save_favorite_guarded',
      'save_favorite_player_guarded',
      'save_match_reminder_guarded',
      'personal_write_guard_contract',
      'claim_provider_incident_alert_delivery',
      'finalize_provider_incident_alert_delivery',
      'provider_incident_alert_delivery_contract',
      'claim_smart_notification_delivery',
      'finalize_smart_notification_delivery',
      'activate_pass_entitlement',
      'consume_pass_entitlement',
      'refund_pass_entitlement_usage',
      'refund_pass_entitlement',
      'backend_readiness_contract'
    )
)
select jsonb_build_object(
  'ok', true,
  'fingerprint', md5(string_agg(part, E'\n' order by part)),
  'parts', count(*),
  'checked_at', now()
)
from parts;
$$;

revoke execute on function public.backend_schema_fingerprint()
  from public, anon, authenticated;
grant execute on function public.backend_schema_fingerprint()
  to service_role;



notify pgrst, 'reload schema';
