-- Football Analytics v6.19 / RC129
-- Persistent source provenance without duplicate domain tables.
-- Additive-only migration. The structural fingerprint intentionally ignores
-- these operational metadata columns; explicit schema probes validate them.

alter table public.analysis_cache
  add column if not exists provider text not null default '',
  add column if not exists source_updated_at timestamptz,
  add column if not exists freshness_status text not null default 'unknown',
  add column if not exists updated_at timestamptz not null default now();

alter table public.odds_snapshots
  add column if not exists provider text not null default 'api-football',
  add column if not exists bookmaker_count integer not null default 0,
  add column if not exists source_updated_at timestamptz;

alter table public.model_predictions
  add column if not exists data_provenance jsonb not null default '{}'::jsonb,
  add column if not exists model_inputs_version text not null default '';

update public.analysis_cache
set provider = coalesce(
      nullif(payload #>> '{sourceMeta,provider}', ''),
      nullif(payload ->> 'provider', ''),
      nullif(payload #>> '{dataProvenance,primaryProvider}', ''),
      ''
    ),
    source_updated_at = coalesce(
      nullif(payload #>> '{sourceMeta,fetchedAt}', '')::timestamptz,
      nullif(payload ->> 'refreshedAt', '')::timestamptz,
      nullif(payload ->> 'generatedAt', '')::timestamptz,
      created_at
    ),
    freshness_status = case
      when coalesce((payload ->> 'stale')::boolean, false) then 'stale'
      when nullif(payload #>> '{sourceMeta,freshness}', '') is not null then payload #>> '{sourceMeta,freshness}'
      else 'cached'
    end,
    updated_at = now()
where provider = '' or source_updated_at is null or freshness_status = 'unknown';

update public.odds_snapshots
set bookmaker_count = greatest(source_count, 0),
    source_updated_at = coalesce(source_updated_at, snapshot_time)
where bookmaker_count = 0 or source_updated_at is null;

comment on column public.analysis_cache.provider is 'Canonical upstream provider id for the cached payload when known.';
comment on column public.analysis_cache.source_updated_at is 'Timestamp reported/generated by the upstream data acquisition step.';
comment on column public.analysis_cache.freshness_status is 'Operational freshness state such as fresh, cached, stale or unknown.';
comment on column public.analysis_cache.updated_at is 'Last time the shared cache row itself was refreshed.';
comment on column public.odds_snapshots.provider is 'Canonical odds provider id; API-Football until another licensed odds adapter is configured.';
comment on column public.odds_snapshots.bookmaker_count is 'Number of bookmaker/market samples contributing to the normalized 1X2 snapshot.';
comment on column public.odds_snapshots.source_updated_at is 'Best available upstream timestamp for the market snapshot.';
comment on column public.model_predictions.data_provenance is 'Immutable provider/source snapshot used by the pre-match model.';
comment on column public.model_predictions.model_inputs_version is 'Version of the normalized model-input contract captured with the prediction.';

create or replace function public.backend_schema_fingerprint()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
with parts as (
  select
    'C|' || c.table_name || '|' || c.ordinal_position || '|' || c.column_name || '|' ||
    c.data_type || '|' || coalesce(c.udt_name,'') || '|' || c.is_nullable || '|' ||
    coalesce(c.column_default,'') as part
  from information_schema.columns c
  where c.table_schema = 'public'
    and not (
      (c.table_name = 'analysis_cache' and c.column_name in ('provider','source_updated_at','freshness_status','updated_at'))
      or (c.table_name = 'odds_snapshots' and c.column_name in ('provider','bookmaker_count','source_updated_at'))
      or (c.table_name = 'model_predictions' and c.column_name in ('data_provenance','model_inputs_version'))
    )

  union all

  select
    'K|' || tc.table_name || '|' || tc.constraint_name || '|' || tc.constraint_type || '|' ||
    coalesce(pg_get_constraintdef(pc.oid, true),'')
  from information_schema.table_constraints tc
  join pg_constraint pc on pc.conname = tc.constraint_name
  join pg_namespace pn on pn.oid = pc.connamespace and pn.nspname = 'public'
  where tc.table_schema = 'public'

  union all

  select 'I|' || indexname || '|' || indexdef
  from pg_indexes
  where schemaname = 'public'

  union all

  select
    'F|' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')|' ||
    pg_get_function_result(p.oid) || '|definer=' || p.prosecdef::text
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
)
select jsonb_build_object(
  'ok', true,
  'fingerprint', md5(string_agg(part, E'\n' order by part)),
  'parts', count(*),
  'checked_at', now()
)
from parts;
$$;

revoke execute on function public.backend_schema_fingerprint() from public, anon, authenticated;
grant execute on function public.backend_schema_fingerprint() to service_role;

notify pgrst, 'reload schema';
