-- Football Analytics v6.20 / reliable provider incident alert delivery
-- Additive migration: persistent delivery ledger, distributed atomic claim,
-- explicit ambiguous-delivery state, controlled retry and service-role-only RPCs.
-- No table/column is dropped, renamed or destructively altered.

create table if not exists public.provider_incident_alert_deliveries (
  id bigint generated by default as identity primary key,
  incident_id text not null
    check (char_length(incident_id) between 1 and 200),
  transition text not null
    check (char_length(transition) between 1 and 80),
  alert_key text not null
    check (char_length(alert_key) between 1 and 280),
  destination_key text not null
    check (char_length(destination_key) between 8 and 160),
  destination_slot integer not null default 0
    check (destination_slot >= 0),
  status text not null default 'sending'
    check (status in ('sending','sent','retry_pending','terminal_failed','unknown')),
  attempts integer not null default 0
    check (attempts >= 0),
  claimed_at timestamptz,
  locked_until timestamptz,
  retry_at timestamptz,
  sent_at timestamptz,
  terminal_at timestamptz,
  unknown_at timestamptz,
  last_http_status integer,
  last_error_code text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_incident_alert_delivery_identity
    unique (incident_id, transition, destination_key),
  constraint provider_incident_alert_delivery_alert_destination_key
    unique (alert_key, destination_key)
);

create index if not exists provider_incident_alert_deliveries_incident_created_idx
  on public.provider_incident_alert_deliveries(incident_id, created_at desc);

create index if not exists provider_incident_alert_deliveries_retry_idx
  on public.provider_incident_alert_deliveries(retry_at)
  where status = 'retry_pending';

alter table public.provider_incident_alert_deliveries enable row level security;

revoke all on table public.provider_incident_alert_deliveries from public, anon, authenticated;
grant select, insert, update, delete on table public.provider_incident_alert_deliveries to service_role;
grant usage, select on sequence public.provider_incident_alert_deliveries_id_seq to service_role;

create or replace function public.claim_provider_incident_alert_delivery(
  p_incident_id text,
  p_transition text,
  p_alert_key text,
  p_destination_key text,
  p_destination_slot integer,
  p_max_attempts integer default 3,
  p_lease_seconds integer default 120
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_max_attempts integer := greatest(1, least(coalesce(p_max_attempts,3), 10));
  v_lease_seconds integer := greatest(30, least(coalesce(p_lease_seconds,120), 900));
  v_row public.provider_incident_alert_deliveries%rowtype;
begin
  if p_incident_id is null or btrim(p_incident_id) = ''
     or p_transition is null or btrim(p_transition) = ''
     or p_alert_key is null or btrim(p_alert_key) = ''
     or p_destination_key is null or char_length(btrim(p_destination_key)) < 8
     or p_destination_slot is null or p_destination_slot < 0 then
    return jsonb_build_object(
      'acquired', false,
      'status', 'invalid',
      'reason', 'invalid_input',
      'attempts', 0
    );
  end if;

  insert into public.provider_incident_alert_deliveries(
    incident_id,
    transition,
    alert_key,
    destination_key,
    destination_slot,
    status,
    attempts,
    claimed_at,
    locked_until,
    created_at,
    updated_at
  )
  values (
    left(btrim(p_incident_id),200),
    left(btrim(p_transition),80),
    left(btrim(p_alert_key),280),
    left(btrim(p_destination_key),160),
    p_destination_slot,
    'sending',
    1,
    v_now,
    v_now + make_interval(secs => v_lease_seconds),
    v_now,
    v_now
  )
  on conflict do nothing
  returning * into v_row;

  if found then
    return jsonb_build_object(
      'acquired', true,
      'status', 'sending',
      'reason', 'created',
      'attempts', v_row.attempts,
      'retryAt', null
    );
  end if;

  select *
  into v_row
  from public.provider_incident_alert_deliveries
  where alert_key = left(btrim(p_alert_key),280)
    and destination_key = left(btrim(p_destination_key),160)
  for update;

  if not found then
    return jsonb_build_object(
      'acquired', false,
      'status', 'invalid',
      'reason', 'identity_conflict',
      'attempts', 0
    );
  end if;

  if v_row.incident_id <> left(btrim(p_incident_id),200)
     or v_row.transition <> left(btrim(p_transition),80) then
    return jsonb_build_object(
      'acquired', false,
      'status', 'invalid',
      'reason', 'identity_mismatch',
      'attempts', v_row.attempts
    );
  end if;

  if v_row.status = 'sent' then
    return jsonb_build_object(
      'acquired', false,
      'status', 'sent',
      'reason', 'already_sent',
      'attempts', v_row.attempts
    );
  end if;

  if v_row.status = 'terminal_failed' then
    return jsonb_build_object(
      'acquired', false,
      'status', 'terminal_failed',
      'reason', 'terminal_failure',
      'attempts', v_row.attempts
    );
  end if;

  if v_row.status = 'unknown' then
    return jsonb_build_object(
      'acquired', false,
      'status', 'unknown',
      'reason', 'ambiguous_delivery_suppressed',
      'attempts', v_row.attempts
    );
  end if;

  if v_row.status = 'sending' then
    if v_row.locked_until is null or v_row.locked_until <= v_now then
      update public.provider_incident_alert_deliveries
      set status = 'unknown',
          unknown_at = v_now,
          locked_until = null,
          last_error_code = 'STALE_SENDING_LEASE',
          last_error = 'Delivery lease expired before the Telegram result was durably finalized.',
          updated_at = v_now
      where id = v_row.id
      returning * into v_row;

      return jsonb_build_object(
        'acquired', false,
        'status', 'unknown',
        'reason', 'stale_sending_lease',
        'attempts', v_row.attempts
      );
    end if;

    return jsonb_build_object(
      'acquired', false,
      'status', 'sending',
      'reason', 'in_flight',
      'attempts', v_row.attempts
    );
  end if;

  if v_row.status = 'retry_pending' then
    if v_row.attempts >= v_max_attempts then
      update public.provider_incident_alert_deliveries
      set status = 'terminal_failed',
          retry_at = null,
          terminal_at = coalesce(terminal_at,v_now),
          locked_until = null,
          last_error_code = coalesce(last_error_code,'MAX_ATTEMPTS'),
          last_error = coalesce(last_error,'Maximum automatic delivery attempts reached.'),
          updated_at = v_now
      where id = v_row.id
      returning * into v_row;

      return jsonb_build_object(
        'acquired', false,
        'status', 'terminal_failed',
        'reason', 'max_attempts',
        'attempts', v_row.attempts
      );
    end if;

    if v_row.retry_at is not null and v_row.retry_at > v_now then
      return jsonb_build_object(
        'acquired', false,
        'status', 'retry_pending',
        'reason', 'retry_not_due',
        'attempts', v_row.attempts,
        'retryAt', v_row.retry_at
      );
    end if;

    update public.provider_incident_alert_deliveries
    set status = 'sending',
        attempts = attempts + 1,
        claimed_at = v_now,
        locked_until = v_now + make_interval(secs => v_lease_seconds),
        retry_at = null,
        updated_at = v_now
    where id = v_row.id
    returning * into v_row;

    return jsonb_build_object(
      'acquired', true,
      'status', 'sending',
      'reason', 'retry_acquired',
      'attempts', v_row.attempts,
      'retryAt', null
    );
  end if;

  return jsonb_build_object(
    'acquired', false,
    'status', coalesce(v_row.status,'invalid'),
    'reason', 'unsupported_state',
    'attempts', v_row.attempts
  );
end;
$$;

create or replace function public.finalize_provider_incident_alert_delivery(
  p_alert_key text,
  p_destination_key text,
  p_status text,
  p_retry_at timestamptz default null,
  p_http_status integer default null,
  p_error_code text default null,
  p_error_message text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_status text := btrim(coalesce(p_status,''));
  v_row public.provider_incident_alert_deliveries%rowtype;
begin
  if p_alert_key is null or btrim(p_alert_key) = ''
     or p_destination_key is null or btrim(p_destination_key) = ''
     or v_status not in ('sent','retry_pending','terminal_failed','unknown') then
    return jsonb_build_object('ok',false,'reason','invalid_input');
  end if;

  update public.provider_incident_alert_deliveries
  set status = v_status,
      locked_until = null,
      retry_at = case when v_status = 'retry_pending' then p_retry_at else null end,
      sent_at = case when v_status = 'sent' then v_now else sent_at end,
      terminal_at = case when v_status = 'terminal_failed' then v_now else terminal_at end,
      unknown_at = case when v_status = 'unknown' then v_now else unknown_at end,
      last_http_status = p_http_status,
      last_error_code = nullif(left(coalesce(p_error_code,''),80),''),
      last_error = nullif(left(coalesce(p_error_message,''),240),''),
      updated_at = v_now
  where alert_key = left(btrim(p_alert_key),280)
    and destination_key = left(btrim(p_destination_key),160)
    and status = 'sending'
  returning * into v_row;

  if not found then
    select *
    into v_row
    from public.provider_incident_alert_deliveries
    where alert_key = left(btrim(p_alert_key),280)
      and destination_key = left(btrim(p_destination_key),160);

    return jsonb_build_object(
      'ok', false,
      'reason', 'not_sending',
      'status', coalesce(v_row.status,'missing')
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'status', v_row.status,
    'attempts', v_row.attempts,
    'retryAt', v_row.retry_at
  );
end;
$$;

create or replace function public.provider_incident_alert_delivery_contract()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
with checks as (
  select
    to_regclass('public.provider_incident_alert_deliveries') is not null as table_ok,
    to_regprocedure('public.claim_provider_incident_alert_delivery(text,text,text,text,integer,integer,integer)') is not null as claim_ok,
    to_regprocedure('public.finalize_provider_incident_alert_delivery(text,text,text,timestamp with time zone,integer,text,text)') is not null as finalize_ok,
    exists (
      select 1
      from pg_constraint
      where conrelid = 'public.provider_incident_alert_deliveries'::regclass
        and conname = 'provider_incident_alert_delivery_identity'
        and contype = 'u'
    ) as identity_ok,
    exists (
      select 1
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public'
        and c.relname = 'provider_incident_alert_deliveries'
        and c.relrowsecurity
    ) as rls_ok
)
select jsonb_build_object(
  'ok', table_ok and claim_ok and finalize_ok and identity_ok and rls_ok,
  'version', 'v1',
  'table', table_ok,
  'claimRpc', claim_ok,
  'finalizeRpc', finalize_ok,
  'uniqueIdentity', identity_ok,
  'rls', rls_ok
)
from checks;
$$;

-- Keep the existing structural fingerprint stable during the migration/deploy
-- boundary. v6.20 objects are verified by the dedicated delivery contract above.
create or replace function public.backend_schema_fingerprint()
returns jsonb
language sql
stable
security invoker
set search_path = public, pg_catalog, pg_temp
as $$
with parts as (
  select
    'C|' || c.table_name || '|' || c.ordinal_position || '|' || c.column_name || '|' ||
    c.data_type || '|' || coalesce(c.udt_name,'') || '|' || c.is_nullable || '|' ||
    coalesce(c.column_default,'') as part
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name <> 'provider_incident_alert_deliveries'
    and not (
      (c.table_name = 'analysis_cache' and c.column_name in ('provider','source_updated_at','freshness_status','updated_at'))
      or (c.table_name = 'odds_snapshots' and c.column_name in ('provider','bookmaker_count','source_updated_at'))
      or (c.table_name = 'model_predictions' and c.column_name in ('data_provenance','model_inputs_version'))
    )

  union all

  select
    'K|' || tc.table_name || '|' || tc.constraint_name || '|' || tc.constraint_type || '|' ||
    coalesce(pg_get_constraintdef(pc.oid, true),'')
  from information_schema.table_constraints tc
  join pg_constraint pc on pc.conname = tc.constraint_name
  join pg_namespace pn on pn.oid = pc.connamespace and pn.nspname = 'public'
  where tc.table_schema = 'public'
    and tc.table_name <> 'provider_incident_alert_deliveries'

  union all

  select 'I|' || indexname || '|' || indexdef
  from pg_indexes
  where schemaname = 'public'
    and tablename <> 'provider_incident_alert_deliveries'

  union all

  select
    'F|' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')|' ||
    pg_get_function_result(p.oid) || '|definer=' || p.prosecdef::text
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname not in (
      'save_favorite_guarded',
      'save_match_reminder_guarded',
      'personal_write_guard_contract',
      'claim_provider_incident_alert_delivery',
      'finalize_provider_incident_alert_delivery',
      'provider_incident_alert_delivery_contract'
    )
)
select jsonb_build_object(
  'ok', true,
  'fingerprint', md5(string_agg(part, E'\n' order by part)),
  'parts', count(*),
  'checked_at', now()
)
from parts;
$$;

revoke execute on function public.claim_provider_incident_alert_delivery(text,text,text,text,integer,integer,integer) from public, anon, authenticated;
revoke execute on function public.finalize_provider_incident_alert_delivery(text,text,text,timestamptz,integer,text,text) from public, anon, authenticated;
revoke execute on function public.provider_incident_alert_delivery_contract() from public, anon, authenticated;
revoke execute on function public.backend_schema_fingerprint() from public, anon, authenticated;

grant execute on function public.claim_provider_incident_alert_delivery(text,text,text,text,integer,integer,integer) to service_role;
grant execute on function public.finalize_provider_incident_alert_delivery(text,text,text,timestamptz,integer,text,text) to service_role;
grant execute on function public.provider_incident_alert_delivery_contract() to service_role;
grant execute on function public.backend_schema_fingerprint() to service_role;

notify pgrst, 'reload schema';
