-- Football Analytics v6.15 / RC53
-- First-party media-launch attribution and conversion funnel.

alter table public.users
  add column if not exists acquisition_source text not null default '',
  add column if not exists acquisition_campaign text not null default '',
  add column if not exists acquisition_content text not null default '',
  add column if not exists acquisition_start_param text not null default '',
  add column if not exists acquisition_first_touch_at timestamptz;

create table if not exists public.growth_events (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  event_name text not null,
  channel text not null default 'telegram',
  fixture_id bigint,
  source text not null default '',
  campaign text not null default '',
  content text not null default '',
  event_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint growth_events_event_name_check
    check (event_name ~ '^[a-z0-9_]{2,40}$'),
  constraint growth_events_channel_check
    check (channel in ('telegram','miniapp','system')),
  constraint growth_events_metadata_object_check
    check (jsonb_typeof(metadata) = 'object')
);

create unique index if not exists growth_events_event_key_uidx
  on public.growth_events(event_key)
  where event_key is not null and event_key <> '';

create index if not exists growth_events_event_created_idx
  on public.growth_events(event_name, created_at desc);

create index if not exists growth_events_campaign_created_idx
  on public.growth_events(source, campaign, created_at desc);

create index if not exists growth_events_user_created_idx
  on public.growth_events(telegram_id, created_at desc);

alter table public.growth_events enable row level security;

revoke all on table public.growth_events from anon, authenticated;
revoke all on sequence public.growth_events_id_seq from anon, authenticated;
grant select, insert, delete on table public.growth_events to service_role;
grant usage, select on sequence public.growth_events_id_seq to service_role;

comment on table public.growth_events is
  'RC53 backend-only first-party acquisition and product-funnel events. No third-party advertising identifiers.';
comment on column public.users.acquisition_first_touch_at is
  'RC53 immutable first attributed entry into FM AI; subsequent starts must not overwrite it.';

notify pgrst, 'reload schema';
